# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YvYomDbu0BcjjyHkCjVX-aveynf6zlfR
"""

import pandas as pd

df = pd.read_csv('analysis_id(in).csv')


df['win_count'] = df['win_count'].fillna(0)


df['total_wins'] = df['prebid_win_count'] + df['win_count']


grouped = df.groupby('bidder').agg(
    total_wins=('total_wins', 'sum'),
    total_requests=('request_count', 'sum')
)


grouped['win_rate'] = (grouped['total_wins'] / grouped['total_requests']) * 100


grouped = grouped.sort_values(by='win_rate', ascending=False)


print(grouped[['win_rate', 'total_wins', 'total_requests']])

